### ISSUE TITLE
最后一项测试.trace文件没反应

### ISSUE THREAD

**Issue by mayuweiya** [jiangxincode/CacheSim#2]
把exe文件删除容纳后重新构建，其他一切正常，只有最后一项输入路径测试.trace文件时一直没反应

**Comment by jiangxincode** [comment]
是完全没有反应么？可能是因为运行所需的时间比较长，你可以使用其中的jiangxin.trace这个文件做下测试，这个文件数据量比较小。

**Comment by mayuweiya** [comment]
谢谢啦，我现在不知道为啥已经可以运行了，挺莫名其妙的......

**Comment by jiangxincode** [comment]
好的，我先关闭改issue了，有问题再说哈
