### ISSUE TITLE
如何获取hit到哪一层

### ISSUE THREAD

**Issue by MichaelWU0726** [jiangxincode/CacheSim#5]
看了源码中只是记录了访存是hit还是miss，未记录是hit到L1/L2还是LLC。如何修改代码实现呢

**Comment by jiangxincode** [comment]
我能想到的是实现变化：

* 定义状态变量：在你的缓存模拟器中，为每个缓存级别定义状态变量，以记录当前的命中情况。
* 更新访问函数：在处理缓存访问的函数中，添加逻辑来检查访问是否命中了L1、L2或LLC。
* 记录命中信息：每当发生命中时，更新相应的状态变量，并记录命中的级别。

cache_item就不能使用std::bitset<32>了，要考虑使用更大的bitset
