### ISSUE TITLE
cache_item[31]即valid位疑惑

### ISSUE THREAD

**Issue by LEEXXX1024** [jiangxincode/CacheSim#6]
代码中valid似乎无用，最开始于CreateCache.cpp: 19一直置为1
反而代码中使用cache_item[30]即hit位来表示该数据是真的从mem中拿出来，即完成我们一般所指的valid位的作用
所以是不是hit位完全多余，不需要将valid最开始置1

此外InitVariables.cpp:5-13 似乎是无用的，根据main的执行顺序，此时的i_num_line应该为base.cpp中的0，所以该段代码似乎不执行

**Comment by jiangxincode** [comment]
> 代码中valid似乎无用，最开始于CreateCache.cpp: 19一直置为1
反而代码中使用cache_item[30]即hit位来表示该数据是真的从mem中拿出来，即完成我们一般所指的valid位的作用
所以是不是hit位完全多余，不需要将valid最开始置1

当前实际使用的是cache_item[30]作为是否名中的标记，valid暂时无用

> 此外InitVariables.cpp:5-13 似乎是无用的，根据main的执行顺序，此时的i_num_line应该为base.cpp中的0，所以该段代码似乎不执行

对于首次执行时，这段代码确实是没有意义的，但是这个程序是可以重复执行的，所以在后面的执行时要保证数据的干净

```cpp
int main(int argc, char* argv[])
{
	char ch = '\0';

	do
	{
		InitVariables();
		GetInput();
		CalcInfo();
		CreateCache();
		FileTest();
		PrintOutput();
		std::cout << "Continue/Exit(C/E)" << std::endl;
		std::cin >> ch;
	} while ((ch != 'e') && (ch != 'E'));

	return 0;
}
```

**Comment by LEEXXX1024** [comment]
非常感谢
